<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
    'small_image',
    'name',
    'short_description'
))
    ->addFieldToFilter('visibility', array(
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
    ))//showing just products visible in catalog or both search and catalog
    ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
    ->getSelect()
    ->where('price_index.final_price < price_index.price')
    ->limit(4)//we can specify how many products we want to show on this page
    ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
;


$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2><?php echo $this->__('Sản phẩm khuyến mại'); ?></h2>
        </div>
        <div class="category-products">
            <?php $_columnCount = 4; ?>
            <?php $i = 0; ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                        <?php $_imgSize = 210; ?>
                        <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                           class="product-image">
                            <img
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>"
                                alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                        </a>
                        <div class="product-info">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h3>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <div class="actions">
                                <?php if ($_product->isSaleable()): ?>
                                    <button type="button"
                                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                            class="button btn-cart"
                                            onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>"
                                               class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                                class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>